-- ============================================================
-- Onboardly — Client Onboarding Automation
-- Database Schema v1.0
-- Generated by DB Architect (#12)
-- ============================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================
-- USERS (freelancer accounts)
-- ============================================================
CREATE TABLE users (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email         VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  name          VARCHAR(255) NOT NULL,
  plan          VARCHAR(50)  NOT NULL DEFAULT 'free',  -- free | starter | pro
  stripe_customer_id VARCHAR(255),
  stripe_subscription_id VARCHAR(255),
  trial_ends_at TIMESTAMPTZ,
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_stripe_customer ON users(stripe_customer_id);

-- ============================================================
-- CLIENTS
-- ============================================================
CREATE TABLE clients (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name             VARCHAR(255) NOT NULL,
  email            VARCHAR(255) NOT NULL,
  company          VARCHAR(255),
  phone            VARCHAR(50),
  status           VARCHAR(50) NOT NULL DEFAULT 'new',          -- new | active | completed | archived
  onboarding_stage VARCHAR(50) NOT NULL DEFAULT 'intake',       -- intake | documents | review | complete
  notes            TEXT,
  metadata         JSONB,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_clients_user_id ON clients(user_id);
CREATE INDEX idx_clients_status ON clients(status);
CREATE INDEX idx_clients_email ON clients(user_id, email);
CREATE UNIQUE INDEX idx_clients_user_email ON clients(user_id, email);

-- ============================================================
-- WORKFLOWS (onboarding templates)
-- ============================================================
CREATE TABLE workflows (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name        VARCHAR(255) NOT NULL,
  description TEXT,
  steps       JSONB NOT NULL DEFAULT '[]',
  is_default  BOOLEAN NOT NULL DEFAULT false,
  is_archived BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_workflows_user_id ON workflows(user_id);
CREATE INDEX idx_workflows_is_default ON workflows(user_id, is_default);

-- ============================================================
-- INTAKE FORMS
-- ============================================================
CREATE TABLE intake_forms (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  workflow_id UUID REFERENCES workflows(id) ON DELETE CASCADE,
  title       VARCHAR(255) NOT NULL,
  description TEXT,
  questions   JSONB NOT NULL DEFAULT '[]',
  is_archived BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_intake_forms_user_id ON intake_forms(user_id);
CREATE INDEX idx_intake_forms_workflow_id ON intake_forms(workflow_id);

-- ============================================================
-- ONBOARDING RUNS (active onboarding instances)
-- ============================================================
CREATE TABLE onboarding_runs (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  client_id    UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  workflow_id  UUID NOT NULL REFERENCES workflows(id) ON DELETE RESTRICT,
  current_step INTEGER NOT NULL DEFAULT 1,
  total_steps  INTEGER NOT NULL DEFAULT 1,
  status       VARCHAR(50) NOT NULL DEFAULT 'in_progress',  -- in_progress | completed | abandoned
  progress_pct INTEGER NOT NULL DEFAULT 0,
  started_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  last_activity_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_runs_user_id ON onboarding_runs(user_id);
CREATE INDEX idx_runs_client_id ON onboarding_runs(client_id);
CREATE INDEX idx_runs_status ON onboarding_runs(status);
CREATE INDEX idx_runs_workflow_id ON onboarding_runs(workflow_id);

-- ============================================================
-- DOCUMENTS
-- ============================================================
CREATE TABLE documents (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  onboarding_run_id UUID NOT NULL REFERENCES onboarding_runs(id) ON DELETE CASCADE,
  type              VARCHAR(50) NOT NULL,   -- contract | nda | questionnaire | proposal | invoice
  title             VARCHAR(255) NOT NULL,
  content           JSONB,
  file_url          VARCHAR(1024),
  status            VARCHAR(50) NOT NULL DEFAULT 'pending',  -- pending | sent | viewed | signed | rejected
  sent_at           TIMESTAMPTZ,
  viewed_at         TIMESTAMPTZ,
  signed_at         TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_documents_run_id ON documents(onboarding_run_id);
CREATE INDEX idx_documents_user_id ON documents(user_id);
CREATE INDEX idx_documents_status ON documents(status);

-- ============================================================
-- FORM RESPONSES (client answers to intake forms)
-- ============================================================
CREATE TABLE form_responses (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  onboarding_run_id UUID NOT NULL REFERENCES onboarding_runs(id) ON DELETE CASCADE,
  intake_form_id    UUID NOT NULL REFERENCES intake_forms(id) ON DELETE CASCADE,
  client_id         UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  answers           JSONB NOT NULL DEFAULT '{}',
  submitted_at      TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_form_responses_run_id ON form_responses(onboarding_run_id);
CREATE INDEX idx_form_responses_client_id ON form_responses(client_id);

-- ============================================================
-- EMAIL LOGS (automated email tracking)
-- ============================================================
CREATE TABLE email_logs (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  client_id         UUID REFERENCES clients(id) ON DELETE SET NULL,
  onboarding_run_id UUID REFERENCES onboarding_runs(id) ON DELETE SET NULL,
  type              VARCHAR(100) NOT NULL,  -- welcome | document_request | reminder | completion
  subject           VARCHAR(500) NOT NULL,
  to_email          VARCHAR(255) NOT NULL,
  status            VARCHAR(50) NOT NULL DEFAULT 'queued',  -- queued | sent | failed | bounced
  provider_id       VARCHAR(255),
  sent_at           TIMESTAMPTZ,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_email_logs_user_id ON email_logs(user_id);
CREATE INDEX idx_email_logs_client_id ON email_logs(client_id);

-- ============================================================
-- UPDATED_AT TRIGGER
-- ============================================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_clients_updated_at BEFORE UPDATE ON clients FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_workflows_updated_at BEFORE UPDATE ON workflows FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_intake_forms_updated_at BEFORE UPDATE ON intake_forms FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_documents_updated_at BEFORE UPDATE ON documents FOR EACH ROW EXECUTE FUNCTION update_updated_at();
